version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SESSION_SECRET=local-development-secret
      - FRONTEND_URL=http://localhost:3001
    restart: unless-stopped

volumes:
  postgres_data: 