version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - REACT_APP_API_URL=http://localhost:3001
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SESSION_SECRET=local-development-secret
      - FRONTEND_URL=http://localhost:3001
      # API Keys that users can override via Docker UI
      - NOTION_INTEGRATION_TOKEN=${NOTION_INTEGRATION_TOKEN:-}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY:-}
      # Rate limiting settings
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - SESSION_COOKIE_MAX_AGE=86400000
      # Frontend API URL - this tells the React app where to find the backend
      - REACT_APP_API_URL=http://localhost:3001
    restart: unless-stopped

volumes:
  postgres_data: 