version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:password@db:5432/notion_books_db
      - SESSION_SECRET=your-session-secret-here
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - db
    volumes:
      - ./backend/.env:/app/backend/.env:ro
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=notion_books_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/config/database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 